blueprint:
  name: Homematic(IP) Local Persistent notification
  description: Display persistent notification if device is not available.
    v2026-04-14
  domain: automation
  homeassistant:
    min_version: "2026.3.0"
  source_url: https://github.com/sukramj/homematicip_local/blob/devel/blueprints/automation/homematicip_local_persistent_notification.yaml

mode: restart
max_exceeded: silent

trigger:
  - platform: event
    event_type: homematic.device_availability

action:
  - choose:
      - conditions: "{{ trigger.event.data.unavailable == true }}"
        sequence:
          - action: persistent_notification.create
            data:
              notification_id: "{{ trigger.event.data.identifier }}"
              title: "{{ trigger.event.data.title }}"
              message: "{{ trigger.event.data.message }}"
      - conditions: "{{ trigger.event.data.unavailable == false }}"
        sequence:
          - action: persistent_notification.dismiss
            data:
              notification_id: "{{ trigger.event.data.identifier }}"
